### ISSUE TITLE
Make TransactionMonitor.MAX_CONCURRENT_TRANSACTIONS configurable in Waltz client

### ISSUE THREAD

**Issue by whynick1** [wepay/waltz#10]
Based on ad hoc performance tests, @ymatsuda suggested making max concurrent transactions configurable so that we can increase it to hopefully increase producer speed.

**Comment by abhipardhu** [comment]
Seems to be done already, closing this issue.

https://github.com/wepay/waltz/blob/master/waltz-client/src/main/java/com/wepay/waltz/client/WaltzClientConfig.java#L47

https://github.com/wepay/waltz/blob/master/waltz-client/src/main/java/com/wepay/waltz/client/internal/TransactionMonitor.java#L38
