### ISSUE TITLE
Questions about the blog post

### ISSUE THREAD

**Issue by mackenzie-orange** [wepay/waltz#31]
I just read this [blog][blog] and enjoyed reading it! The length and the technical detail was just right.

I have a few questions:

In _Stream Oriented Processing_ you mention using kafka to let down-stream consumers observe state changes. This enables producers of data and consumers of data to be logically separate. Service X creates data and publishes on kafka, Service Y consumes on kafka and writes to materialized view.

[The diagram][diagram] in the blog shows an application that writes to Waltz and then later writes to a materialized view. Does Waltz allow those responsibilities to be separate like in my example with kafka above? E.g. Service X writes to the log, Service Y consumes changes(??) from the log and updates a materialized view.

---

In the _Limitations and Requirements_:
> We require an application to have a transactional data storage like an SQL database. The database acts as a materialized view of Waltz transaction log.

Is the transactional storage an actual requirement? I thought that Waltz does not care about the views (that's the application's job). Why could I not create a materialized view with MongoDB or ElasticSearch?

---

Distributed KV-stores are all the buzz lately. Does Waltz take an existing KV db off-the-shelf, or did your team roll your own? I initally thought you were using Zookkeeper, but you say it's only used for leader election and cluster stuff.

---

I would love to see more technical posts on this technology. Will Waltz get a Jepsen test? 

[blog]: https://wecode.wepay.com/posts/waltz-a-distributed-write-ahead-log
[diagram]: https://wecode.wepay.com/assets/2019-09-09-waltz-a-distributed-write-ahead-log/basic-idea.png

**Comment by ymatsuda** [comment]
> Does Waltz allow those responsibilities to be separate like in my example with kafka above?

Yes. The same log can be consumed by different services. This is actually the use case we assumed. Note that a producer side should consume own transactions to take advantage of the serializable consistency.

> Is the transactional storage an actual requirement?

The transactionality is required to do updates of the client high-water mark and update of the view together in a single transaction. It may be possible to work this around if the client is just consuming transactions, and an update to the view is always idempotent. You can update the view first then update the client high-water mark. If the client dies between these updates, the client will read and apply the same transaction again after restart, but the idempotency guarantees the eventual consistency.

> Does Waltz take an existing KV db off-the-shelf, or did your team roll your own?

KV-store is not part of Waltz. It is an application developer's choice. We provide a callback class (AbstractClientCallbackForJDBC) for developers to use to integrate with a SQL database.

**Comment by mackenzie-orange** [comment]
> KV-store is not part of Waltz. It is an application developer's choice. We provide a callback class (AbstractClientCallbackForJDBC) for developers to use to integrate with a SQL database.

The KV store is a SQL database? How is waltz expected to scale horizontally?

**Comment by ymatsuda** [comment]
Waltz stores transactions in its own storage system built directly on the file system. And the log is partitioned. So, Waltz scales in a similar way as Kafka does.

An application can use any storage as long as the transactionality requirement is met (or a workaround is feasible).
