### ISSUE TITLE
[Question] Testing speed

### ISSUE THREAD

**Issue by djKooks** [wepay/waltz#51]
Hello,
I'm running on build with test, but seems it takes very long time...:
```
$ ./gradlew clean build
Welcome to Gradle 5.6.1!
...
...
Starting a Gradle Daemon (subsequent builds will be faster)
<===========--> 86% EXECUTING [45m 41s]
> IDLE
> IDLE
> IDLE
> :waltz-tools:test > Executing test com.wepay.waltz.tools.storage.StorageCliTest
> IDLE
> IDLE
> IDLE
> :waltz-tools:test > 32 tests completed
```
Is it okay?

**Comment by whynick1** [comment]
Hi @djKooks , the build should be done in a couple minutes. 45m is unreasonably too long. I suggest you pull from the latest commit and re-run. If it still get stuck, please check JVM's heap size. It might be caused by short of memory.

**Comment by djKooks** [comment]
@whynick1 thanks! It has been improved as:
```
$ ./gradlew clean build
...

BUILD SUCCESSFUL in 3m 56s
76 actionable tasks: 76 executed
```

after set as `org.gradle.jvmargs=-Xmx256m`.
Maybe you could add to `gradle.properties` if okay.

Thanks for help.
