### ISSUE TITLE
Make Waltz server StoreSessionImpl.BATCH_SIZE configurable

### ISSUE THREAD

**Issue by whynick1** [wepay/waltz#9]
Based on some ad hoc performance tests, Yasuhiro Matsuda suggested that we might be able to increase producer throughput by increasing the `StoreSessionImpl.BATCH_SIZE`. This is currently hard coded, and we should make it configurable.

**Comment by abhipardhu** [comment]
Merged, https://github.com/wepay/waltz/commit/a8e304d7017f3996218b4ec33071c779381e4b73
